# Generated by Django 5.2.6 on 2025-09-06 18:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(blank=True, default=accounts.models.gen_invite_code, editable=False, max_length=32),
        ),
    ]
