# Generated by Django 5.2.6 on 2025-09-06 18:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_invite_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(default=accounts.models.gen_invite_code, editable=False, max_length=32, unique=True),
        ),
    ]
