# Generated by Django 5.2.6 on 2025-09-06 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_group_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.group'),
        ),
    ]
