# Generated by Django 5.2.6 on 2025-09-06 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.group'),
            preserve_default=False,
        ),
    ]
